DROP DATABASE IF EXISTS redtea;
CREATE DATABASE redtea DEFAULT CHARSET UTF8;
use redtea;

CREATE TABLE movie
(
    ID INT NOT NULL,
    NAME NVARCHAR(80) NOT NULL UNIQUE,
    INTRODUCTION TEXT DEFAULT NULL,
    DIRECTOR NVARCHAR(60) DEFAULT NULL,
    ACTOR TEXT DEFAULT NULL,
    FLAG_TIME CHAR(4) DEFAULT NULL,
    FLAG_AREA CHAR(8) DEFAULT NULL,
    FLAG_TYPE NVARCHAR(20) DEFAULT NULL,
    SCORE FLOAT DEFAULT 8.0,
    URL_IMG TEXT DEFAULT NULL,
    UPDATE_TIME DATE NOT NULL,
    URL TEXT DEFAULT NULL,
    PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE tvseries
(
    ID INT NOT NULL,
    NAME NVARCHAR(80) NOT NULL UNIQUE,
    INTRODUCTION TEXT DEFAULT NULL,
    DIRECTOR NVARCHAR(60) DEFAULT NULL,
    ACTOR TEXT DEFAULT NULL,
    FLAG_TIME CHAR(4) DEFAULT NULL,
    FLAG_AREA CHAR(8) DEFAULT NULL,
    FLAG_TYPE NVARCHAR(20) DEFAULT NULL,
    SCORE FLOAT DEFAULT 8.0,
    URL_IMG TEXT DEFAULT NULL,
    UPDATE_TIME DATE NOT NULL,
    PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE VARiety
(
    ID INT NOT NULL,
    NAME NVARCHAR(80) NOT NULL UNIQUE,
    INTRODUCTION TEXT DEFAULT NULL,
    DIRECTOR NVARCHAR(60) DEFAULT NULL,
    ACTOR TEXT DEFAULT NULL,
    FLAG_TIME CHAR(4) DEFAULT NULL,
    FLAG_AREA CHAR(8) DEFAULT NULL,
    FLAG_TYPE NVARCHAR(20) DEFAULT NULL,
    SCORE FLOAT DEFAULT 8.0,
    URL_IMG TEXT DEFAULT NULL,
    UPDATE_TIME DATE NOT NULL,
    PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE anime
(
    ID INT NOT NULL,
    NAME NVARCHAR(80) NOT NULL UNIQUE,
    INTRODUCTION TEXT DEFAULT NULL,
    DIRECTOR NVARCHAR(60) DEFAULT NULL,
    ACTOR TEXT DEFAULT NULL,
    FLAG_TIME CHAR(4) DEFAULT NULL,
    FLAG_AREA CHAR(8) DEFAULT NULL,
    FLAG_TYPE NVARCHAR(20) DEFAULT NULL,
    SCORE FLOAT DEFAULT 8.0,
    URL_IMG TEXT DEFAULT NULL,
    UPDATE_TIME DATE NOT NULL,
    PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE u_tvseries
(
    VID INT NOT NULL,
    NUM SMALLINT UNSIGNED NOT NULL,
    URL TEXT DEFAULT NULL,
    PRIMARY KEY (VID,NUM)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE u_VARiety
(
    VID INT NOT NULL,
    NUM SMALLINT UNSIGNED NOT NULL,
    URL TEXT DEFAULT NULL,
    PRIMARY KEY (VID,NUM)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE u_anime
(
    VID INT NOT NULL,
    NUM SMALLINT UNSIGNED NOT NULL,
    URL TEXT DEFAULT NULL,
    PRIMARY KEY (VID,NUM)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE ranking
(
	VID CHAR(8) NOT NULL,
    RDAY INT DEFAULT 0,
    RWEEK INT DEFAULT 0,
    RMONTH INT DEFAULT 0,
    PRIMARY KEY(VID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE begfilm
(
	ID INT AUTO_INCREMENT,
	IP CHAR(15) NOT NULL,
	TTIME DATETIME NOT NULL,
	CONTENT text NOT NULL,
	PRIMARY KEY(ID)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE feedback
(
	ID INT AUTO_INCREMENT,
	IP CHAR(15) NOT NULL,
	TTIME DATETIME NOT NULL,
	URL VARCHAR(60) NOT NULL,
	CONTENT text NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE carousel
(
    ID INT NOT NULL,
    URL TEXT NOT NULL,
    NAME NVARCHAR(60) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
